name: secp256k1-haskell
version: 0.2.1
synopsis: Bindings for secp256k1 library from Bitcoin Core
description: Sign and verify signatures using the very fast C secp256k1 library from Pieter Wuille. Has Haskell types and abstractions for keys and signatures.
category: Crypto
author: Jean-Pierre Rupp
maintainer: jprupp@protonmail.ch
copyright: (c) 2017 Jean-Pierre Rupp
license: PublicDomain
license-file: UNLICENSE
github: haskoin/secp256k1-haskell.git
homepage: http://github.com/haskoin/secp256k1-haskell#readme
extra-source-files:
  - CHANGELOG.md
  - README.md
dependencies:
  - base >=4.8 && <5
  - base16-bytestring
  - bytestring
  - cereal
  - entropy
  - deepseq
  - hashable
  - QuickCheck
  - string-conversions
library:
  source-dirs: src
  pkg-config-dependencies:
    - libsecp256k1
  when:
  - condition: flag(ecdh)
    cpp-options: -DECDH
  - condition: flag(schnorr)
    cpp-options: -DSCHNORR
  - condition: flag(recovery)
    cpp-options: -DRECOVERY
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    verbatim:
      build-tool-depends:
          hspec-discover:hspec-discover
    dependencies:
      - hspec
      - secp256k1-haskell
      - mtl
      - HUnit
flags:
  ecdh:
    description: "Enable (experimental) ECDH APIs"
    manual: true
    default: false
  schnorr:
    description: "Enable BIP-340 (Schnorr) APIs"
    manual: true
    default: false
  recovery:
    description: "Enable signature key recovery APIs"
    manual: true
    default: false
