name: secp256k1-haskell-recovery
version: 0.1.0
synopsis: Bindings for recoverable signatures feature of secp256k1
description: Sign and verify recoverable signatures using the secp256k1 library.
category: Crypto
author: Evgeny Osipenko
maintainer: jprupp@protonmail.ch
copyright: (c) 2023 Evgeny Osipenko
license: MIT
license-file: LICENSE
github: haskoin/secp256k1-haskell
homepage: http://github.com/haskoin/secp256k1-haskell#readme
extra-source-files:
  - CHANGELOG.md
dependencies:
  - base >=4.9 && <5
  - base16 >=1.0
  - bytestring >=0.10.8 && <0.12
  - entropy >=0.3.8 && <0.5
  - deepseq >=1.4.2 && <1.5
  - hashable >=1.2.6 && <1.5
  - QuickCheck >=2.9.2 && <2.15
  - secp256k1-haskell
  - string-conversions >=0.4 && <0.5
  - unliftio-core >=0.1.0 && <0.3
library:
  source-dirs: src
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    verbatim:
      build-tool-depends:
          hspec-discover:hspec-discover
    dependencies:
      - hspec
      - secp256k1-haskell-recovery
      - monad-par
      - mtl
      - HUnit
